image: "cuaesd/aesd-autotest"

variables:
    GIT_SUBMODULE_STRATEGY: recursive

test:
    script:
        - git config --global http.sslVerify false
        - git submodule update --init --recursive
        - ./test.sh
