name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Update submodules with Debug
            run: |
                  # 1. Forçar HTTPS e desativar verificação de SSL (por causa da data de 2026)
                  git config --global url."https://gitlab.com/".insteadOf git://gitlab.com/
                  git config --global http.sslVerify false
          
                  # 2. Ativar logs detalhados (isso vai gerar a info que você quer ver)
                  export GIT_CURL_VERBOSE=1
                  export GIT_TRACE=1
          
              # Tenta o update com as flags de segurança que discutimos
              #git -c http.sslVerify=false submodule update --init --recursive
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
