name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git -c http.sslVerify=false submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Disable Wget SSL Verification
            run: echo "check_certificate = off" >> ~/.wgetrc
          - name: Pre-download zlib to correct folder
            run:|
                  # Criar diretório onde o Buildroot procura tarballs
                  mkdir -p buildroot/dl

                  # Fazer download ignorando certificados SSL
                  wget --no-check-certificate \
                  -O buildroot/dl/zlib-1.3.2.tar.xz \
                  https://github.com/madler/zlib/archive/refs/tags/v1.3.2.tar.gz
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full_test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
