name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Debug and Update Submodules
            run: |
              # Ativa logs detalhados de rede e performance do Git
                  export GIT_TRACE=1
                  export GIT_CURL_VERBOSE=1
                  export GIT_TRACE_PACKET=1
              
              # Tenta o update com as flags de segurança que discutimos
              #git -c http.sslVerify=false submodule update --init --recursive
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
